#!/bin/bash
# Watch setup of core.tcl.tk, and personal
# # ## ### ##### ######## #############

# email addresses, all local
src=aku
dst=aku

# # ## ### ##### ######## #############

watch=""
watch="$watch http://core.tcl.tk/"
watch="$watch http://core.tcl.tk/tcl"
watch="$watch http://core.tcl.tk/tk"
watch="$watch http://core.tcl.tk/thread"
watch="$watch http://core.tcl.tk/tcloo"
watch="$watch http://core.tcl.tk/tclconfig"
watch="$watch http://core.tcl.tk/sampleextension"
watch="$watch http://core.tcl.tk/tclws"
watch="$watch http://core.tcl.tk/itcl"
watch="$watch http://core.tcl.tk/itk"
watch="$watch http://core.tcl.tk/iwidgets"
watch="$watch http://core.tcl.tk/tdbc"
watch="$watch http://core.tcl.tk/tdbcmysql"
watch="$watch http://core.tcl.tk/tdbcodbc"
watch="$watch http://core.tcl.tk/tdbcpostgres"
watch="$watch http://core.tcl.tk/tdbcsqlite3"
#watch="$watch http://core.tcl.tk/tdbc"
watch="$watch http://core.tcl.tk/wtk"
#watch="$watch http://core.tcl.tk/"

watch="$watch http://core.tcl.tk/tcllib"
watch="$watch http://core.tcl.tk/tklib"
watch="$watch http://core.tcl.tk/tclapps"
watch="$watch http://core.tcl.tk/bwidget"
watch="$watch http://core.tcl.tk/mclistbox"
watch="$watch http://core.tcl.tk/widget"
watch="$watch http://core.tcl.tk/tclbench"
#watch="$watch http://core.tcl.tk/"

watch="$watch http://core.tcl.tk/akupries/array"
watch="$watch http://core.tcl.tk/akupries/atom"
watch="$watch http://core.tcl.tk/akupries/backup"
watch="$watch http://core.tcl.tk/akupries/blob"
watch="$watch http://core.tcl.tk/akupries/change"
watch="$watch http://core.tcl.tk/akupries/cmdr"
watch="$watch http://core.tcl.tk/akupries/crimp"
watch="$watch http://core.tcl.tk/akupries/crunch"
watch="$watch http://core.tcl.tk/akupries/dbutil"
watch="$watch http://core.tcl.tk/akupries/famfamfam"
watch="$watch http://core.tcl.tk/akupries/fossil2git"
watch="$watch http://core.tcl.tk/akupries/kettle"
watch="$watch http://core.tcl.tk/akupries/kinetcl"
watch="$watch http://core.tcl.tk/akupries/linenoise-utilities"
watch="$watch http://core.tcl.tk/akupries/parsetools"
watch="$watch http://core.tcl.tk/akupries/struct"
watch="$watch http://core.tcl.tk/akupries/tclyaml"
#watch="$watch http://core.tcl.tk/akupries/"

# # ## ### ##### ######## #############

watch-init

for r in $watch
do
  watch-setup "$r" "$src"
  watch-add   "$r" "$dst"
done


# # ## ### ##### ######## #############
exit
