#!/bin/bash
## sed is used to prepend each line with a timestamp.
now=$(date)
echo ================================================================
fx note deliver -R "$1" 2>&1 | sed -e "s|^|${now} @	|"
