[subsection {Changes for version 1}]

This is the first release of [vset PROJECT], packages and application.
The changes therefore describe the initial features of the system.

[para] In detail:

[list_begin enumerated]
[comment {- - -- --- ----- -------- ------------- ---------------------}]
[enum] 	[vset PROJECT] requires Tcl 8.5 or higher. Tcl 8.4 or less is not
	supported.

[comment {- - -- --- ----- -------- ------------- ---------------------}]

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[list_end]
