[comment {-*- tcl -*- --- !doctools --- manpage}]
[comment {- - -- --- ----- -------- ------------- ---------------------}]
[section {Bugs, Ideas, Feedback}]

This document, and the package it describes, will undoubtedly contain
bugs and other problems.

Please report such at the [uri [vset P_LOCATION_1] "[vset PROJECT] Tracker"].

Please also report any ideas for enhancements you may have for either
package and/or documentation.
